#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; CI=ROOT/'morocco26'/'data'/'goal100'/'e_collect'/'candidate_intelligence_v2'
POWER=CI/'candidate_intelligence_v2_multipart_head_power_gate_v4.json'; SCORE=CI/'candidate_intelligence_v2_multipart_predictive_gate_v2.json'; PJD=CI/'candidate_intelligence_v2_predictive_gate_v1.json'; FC=CI/'candidate_intelligence_v2_feature_c_power_gate_v1.json'; OUT=CI/'candidate_intelligence_v2_terminal_certificate_v2.json'
def rj(p):return json.loads(Path(p).read_text(encoding='utf-8'))
def main():
    power=rj(POWER); pjd=rj(PJD); fc=rj(FC)
    if power['status']!='PASS_MULTIPART_HEAD_POWER': score=None; decision='NO_GO_E_REASON_V2_MULTIPART_POWER_INSUFFICIENT'; terminal='TERMINAL_NO_GO'
    else:
        score=rj(SCORE); decision=score['terminal_decision']; terminal='TERMINAL_GO' if decision=='GO_E_REASON_V2_SPEC_FREEZE' else 'TERMINAL_NO_GO'
    out={'schema_version':'2.0','certificate_id':'M26-CANDIDATE-INTELLIGENCE-V2-TERMINAL-CERTIFICATE-V2','purpose':'Final deterministic GO/KILL decision after audited 2021 identity resolution; no further identity resolution or feature expansion is authorized inside this experiment.','power_gate':{'status':power['status'],'eligible_features':power.get('eligible_features',[]),'known_2016':power['2011_TO_2016']['fully_known_all_features'],'known_2021':power['2016_TO_2021']['fully_known_all_features'],'M1_positive_2016':power['2011_TO_2016']['features']['M1_HEAD_PRIOR_MP_SAME_PARTY_SAME_DISTRICT']['positive'],'M1_positive_2021':power['2016_TO_2021']['features']['M1_HEAD_PRIOR_MP_SAME_PARTY_SAME_DISTRICT']['positive'],'audited_identity_resolutions':power.get('identity_resolutions_applied',0)},'predictive_gate':None if score is None else {'terminal_interpretation':score['terminal_interpretation'],'terminal_decision':score['terminal_decision'],'fit_cells':score.get('fit_cells'),'validation_cells':score.get('validation_cells'),'selected_alpha':score.get('selected_alpha'),'beta':score.get('beta'),'pooled_relative_improvement':score.get('validation_2016_TO_2021',{}).get('pooled_relative_improvement'),'bootstrap_probability_model_better':score.get('validation_bootstrap',{}).get('bootstrap_probability_model_better'),'PJD_relative_improvement':score.get('validation_2016_TO_2021',{}).get('by_party',{}).get('PJD',{}).get('relative_improvement'),'RNI_relative_improvement':score.get('validation_2016_TO_2021',{}).get('by_party',{}).get('RNI',{}).get('relative_improvement'),'material_signal_gate':score.get('material_signal_gate')},'prior_diagnostics':{'PJD_only_terminal_interpretation':pjd.get('terminal_interpretation'),'PJD_only_PJD_relative_improvement':pjd.get('validation_comparisons',{}).get('PJD_RMSE',{}).get('relative_improvement'),'feature_C_status':fc.get('status')},'terminal_status':terminal,'terminal_decision':decision,'llm_invoked':False,'F0_modified':False,'2021_blind_status':'RETROSPECTIVE_NOT_BLIND','no_more_post_result_feature_search_inside_this_experiment':True,'next_action':'Freeze E_reason V2 specification before any LLM call; do not tune it on 2021.' if decision=='GO_E_REASON_V2_SPEC_FREEZE' else 'Stop E_reason V2 candidate-intelligence layer and do not invoke Opus on it; preserve data as exploratory evidence and keep F0 unchanged.'}
    OUT.write_text(json.dumps(out,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8'); print(json.dumps({'terminal_status':terminal,'terminal_decision':decision,'power_status':power['status'],'predictive_interpretation':None if score is None else score['terminal_interpretation'],'pooled_relative_improvement':None if score is None else score['validation_2016_TO_2021']['pooled_relative_improvement'],'bootstrap_probability_model_better':None if score is None else score['validation_bootstrap']['bootstrap_probability_model_better']},sort_keys=True))
if __name__=='__main__':main()
