#!/usr/bin/env python3
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];D=R/'data';O=D/'goal75';REP=R/'reports'
def load(p):return json.loads(Path(p).read_text())
def main():
    constitution=load(D/'project_constitution.json');goal=load(D/'execution_goal_75.json');manifest=load(D/'experiment_manifest.json')
    p2=load(O/'p2_exact_audit.json');margins=load(O/'seat_margin_92.json');obs=load(O/'observed_elected_2021.json');kill=load(O/'model_d_kill_preunseal.json');p5=load(O/'p5_live_gate.json')
    phase2=(REP/'PHASE2_EXECUTIVE_FINDINGS.md').read_text();north=constitution['north_star'];checks={};points={}
    checks['P1_FOUNDATION']=(manifest['north_star']==north and constitution['forecast_unlock_gate']['default_status']=='BLOCKED' and manifest['publication_status']=='MECHANISM_EXPERIMENT_NOT_FORECAST')
    points['P1_FOUNDATION']=15 if checks['P1_FOUNDATION'] else 0
    checks['P2_EMPIRICAL_GRAPH']=(p2['local']['constituencies']==92 and p2['local']['seats']==305 and p2['local']['every_constituency_empirically_reproduced'] is True and p2['regional']['constituencies']==12 and p2['regional']['seats']==90 and p2['regional']['every_region_independently_reproduced'] is True and p2['total']['seats']==395 and p2['total']['exact_official_match'] is True and len(margins)==92 and obs['original_elected_rows']==395 and obs['local_seats_observed']==305 and obs['regional_seats_observed']==90 and obs['official_total_exact_match'] is True)
    points['P2_EMPIRICAL_GRAPH']=20 if checks['P2_EMPIRICAL_GRAPH'] else 0
    checks['P3_CAUSAL_SYNTHETIC_SOCIETY']=('PASS_TO_BOUNDED_D_PILOT' in phase2 and '15 blocking gates pass' in phase2 and '0.011352 pp' in phase2 and '3.904684×' in phase2 and manifest['protocol']['protocol_id']=='M26-PHASE2-ABC-D-001')
    points['P3_CAUSAL_SYNTHETIC_SOCIETY']=15 if checks['P3_CAUSAL_SYNTHETIC_SOCIETY'] else 0
    checks['P4_BOUNDED_LLM_SOCIETY_RESOLVED_BY_FALSIFICATION']=(kill['decision']=='KILL_D_FOR_CURRENT_ARCHITECTURE' and kill['decision_stage']=='PRE_HOLDOUT_UNSEAL' and kill['holdout_2021_outcomes_accessed'] is False and kill['contract_validity_rate']<kill['preregistered_contract_validity_rate_min'] and kill['anti_drift']['threshold_changed_after_result'] is False and kill['anti_drift']['prompt_repaired_after_result'] is False and kill['anti_drift']['holdout_used_for_tuning'] is False)
    points['P4_BOUNDED_LLM_SOCIETY_RESOLVED_BY_FALSIFICATION']=15 if checks['P4_BOUNDED_LLM_SOCIETY_RESOLVED_BY_FALSIFICATION'] else 0
    checks['P5_FULL_2026_LIVE_SYSTEM_PARTIAL_GATE']=(p5['gate_pass'] is True and p5['mode']=='PROSPECTIVE_DECODING_NOT_FORECAST' and p5['rows']==92 and p5['gates']['no_quantified_event_effects'] is True and p5['gates']['no_forecast_fields'] is True and p5['gates']['forecast_status_remains_blocked'] is True)
    points['P5_FULL_2026_LIVE_SYSTEM_PARTIAL_GATE']=10 if checks['P5_FULL_2026_LIVE_SYSTEM_PARTIAL_GATE'] else 0
    total=sum(points.values());target=int(goal['target_scientifically_gated_completion_percent']);passed=total>=target
    out={'as_of':'2026-08-16','goal_id':goal['goal_id'],'north_star':north,'scientifically_gated_completion_percent':total,'target_percent':target,'target_reached':passed,'checks':checks,'points':points,'formal_phase':'P5_FULL_2026_LIVE_SYSTEM' if passed else 'BELOW_GOAL75','p4_status':'CLOSED_BY_FALSIFICATION_MODEL_D_KILLED' if checks['P4_BOUNDED_LLM_SOCIETY_RESOLVED_BY_FALSIFICATION'] else 'OPEN','forecast_status':'BLOCKED','remaining_to_100':['deeper P5 empirical 2026 territorial inputs and calibrated prospective uncertainty','P6 pre-election freeze','23 September 2026 real-world scoring and unrevised postmortem']}
    (O/'scientific_completion_75.json').write_text(json.dumps(out,ensure_ascii=False,indent=2))
    if not passed:
        print(json.dumps(out,ensure_ascii=False,indent=2));raise SystemExit(11)
    phase={'as_of':'2026-08-16','formal_phase':'P5_FULL_2026_LIVE_SYSTEM','experimental_frontier':'P6_FREEZE_AND_REALITY_TEST','implementation_completion_percent':max(75,int(load(D/'current_phase.json').get('implementation_completion_percent',0))),'scientifically_gated_completion_percent':total,'status':'GOAL75_REACHED_BY_MACHINE_GATES','completed':['P1 foundation','P2 exact 92 local + 12 regional 2021 replay and full Seat Margin Map','P3 causal synthetic-society experiment','P4 Model D resolved by preregistered falsification/KILL','P5 prospective no-forecast 92-constituency decoding snapshot'],'not_completed':out['remaining_to_100'],'forecast_status':'BLOCKED','agent_society_status':'KILLED_FOR_CURRENT_ARCHITECTURE','goal75_status':'TARGET_REACHED'}
    (D/'current_phase.json').write_text(json.dumps(phase,ensure_ascii=False,indent=2))
    goal.update({'status':'TARGET_REACHED','target_75_reached':True,'completion_at_resolution_percent':total,'resolved_at':'2026-08-16','stop_reason':'Scientifically-gated completion reached target via machine-checkable P1/P2/P3/P4/P5 gates; national forecast remains blocked.'})
    (D/'execution_goal_75.json').write_text(json.dumps(goal,ensure_ascii=False,indent=2))
    report=f'''# MOROCCO//26 — Goal75 scientific checkpoint\n\n**Scientifically gated completion:** {total}%  \n**Goal:** {target}%  \n**Status:** TARGET_REACHED  \n**Forecast:** BLOCKED\n\n## Machine-scored phases\n\n'''+''.join(f'- **{k}: {points[k]} points** — {"PASS" if checks[k] else "FAIL"}\n' for k in points)+'''\n## Architecture decision\n\nModel D / bounded LLM society is **killed for the current architecture** by its preregistered pre-unseal output-contract gate. This is scientific closure by falsification, not a successful LLM result.\n\nThe working architecture at this checkpoint is therefore: empirical electoral graph → exact allocator → structural/statistical baselines → causal non-LLM synthetic experiments where useful → prospective sourced 2026 mechanism decoder.\n\n## What remains\n\nThe remaining 25% is deliberately not credited: deeper 2026 territorial evidence, calibrated prospective uncertainty, the pre-election freeze, and the 23 September reality test.\n'''
    (REP/'GOAL75_75_PERCENT.md').write_text(report);print(json.dumps(out,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
