import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const H={'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization','access-control-allow-methods':'POST, OPTIONS'};
const resp=(o:any,s=200)=>new Response(JSON.stringify(o),{status:s,headers:H});
const result=(id:any,r:any)=>resp({jsonrpc:'2.0',id,result:r});
const error=(id:any,code:number,message:string)=>resp({jsonrpc:'2.0',id,error:{code,message}});
const content=(obj:any)=>({content:[{type:'text',text:JSON.stringify(obj)}],structuredContent:obj});
const BUCKET='asv2-payloads-v1';
const PARTICIPATION_URL=(Deno.env.get('SUPABASE_URL')||'')+'/functions/v1/agent-society-participation';
const hex=(b:Uint8Array)=>Array.from(b).map(x=>x.toString(16).padStart(2,'0')).join('');
const sha256Text=async(s:string)=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))));
async function readText(path:string){const{data,error:e}=await supabase.storage.from(BUCKET).download(path);if(e||!data)throw new Error('PAYLOAD_NOT_READY');return await data.text()}
async function readJson(path:string){return JSON.parse(await readText(path))}
async function payloadFor(workId:string){const{data:w,error:e}=await supabase.from('asv2_work_items').select('anonymous_election_id,anonymous_territory_id,condition_id,batch_id').eq('work_id',workId).single();if(e||!w)throw new Error('WORK_NOT_FOUND');const voter=`voter_batches/${w.anonymous_election_id}/${w.anonymous_territory_id}/${w.batch_id}.json`,context=`contexts/${w.anonymous_election_id}/${w.condition_id}/${w.anonymous_territory_id}.json`;const[judge_prompt,output_schema,ctx,voter_batch]=await Promise.all([readText('as2_full_environment_prompt_v2.md'),readJson('as2_full_environment_output_schema_v2.json'),readJson(context),readJson(voter)]);return{judge_prompt,output_schema,context:ctx,voter_batch}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return resp({error:'POST_ONLY'},405);let m:any;try{m=await req.json()}catch{return resp({error:'INVALID_JSON'},400)};const id=m.id??null,method=m.method;
if(method==='initialize')return result(id,{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'Societe artificielle du Maroc',version:'3.0.0'}});
if(method==='notifications/initialized')return new Response(null,{status:202,headers:H});if(method==='ping')return result(id,{});
if(method==='tools/list')return result(id,{tools:[{name:'voir_la_progression',description:'Donne l’avancement public de la société artificielle, sans révéler les résultats.',inputSchema:{type:'object',properties:{},additionalProperties:false}},{name:'participer',description:'Consomme un ticket de participation obtenu après la vérification anti-abus sur le site ATLAS, puis réserve un lot Claude.',inputSchema:{type:'object',required:['participation_ticket'],properties:{participation_ticket:{type:'string',minLength:20}},additionalProperties:false}},{name:'enregistrer_ma_contribution',description:'Enregistre une contribution terminée. La validation stricte et les contrôles anti-poisoning sont appliqués côté serveur.',inputSchema:{type:'object',required:['claim_token','output_rows'],properties:{claim_token:{type:'string'},model_label:{type:'string'},output_rows:{type:'array',minItems:32,maxItems:32,items:{type:'object'}}},additionalProperties:false}}]});
if(method==='tools/call'){const name=m.params?.name,args=m.params?.arguments||{};try{
if(name==='voir_la_progression'){const r=await fetch(PARTICIPATION_URL+'/status',{headers:{'accept':'application/json'}}),j=await r.json();return result(id,content({completed:Number(j?.completed||0),target:Number(j?.target||2944),results_revealed:false,protection_ready:!!j?.protection_ready}));}
if(name==='participer'){const raw=String(args.participation_ticket||'');if(raw.length<20)return result(id,{isError:true,...content({status:'TICKET_REQUIS',instruction:'Obtenez d’abord un ticket anti-abus sur le site ATLAS.'})});const ticketHash=await sha256Text(raw);const{data,error:e}=await supabase.rpc('asv2_claim_public_work_item_v2',{p_provider:'claude',p_ticket_hash:ticketHash,p_browser_hash:'',p_channel:'mcp'});if(e){const msg=e.message||'';if(msg.includes('NO_READY_WORK_AVAILABLE'))return result(id,{isError:true,...content({status:'AUCUN_LOT_DISPONIBLE'})});if(msg.includes('PARTICIPATION_TICKET')||msg.includes('RATE_LIMIT')||msg.includes('COOLDOWN'))return result(id,{isError:true,...content({status:'TICKET_INVALIDE_OU_LIMITE'})});throw e;}const x=data?.[0],payload=await payloadFor(x.work_id);return result(id,content({claim_token:x.claim_token,expires_at:x.expires_at,payload,regle:'Utilise uniquement ce qui est fourni. Prends chaque décision indépendamment. N’utilise aucune source extérieure, puis appelle enregistrer_ma_contribution.'}));}
if(name==='enregistrer_ma_contribution'){const r=await fetch(PARTICIPATION_URL+'/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({claim_token:String(args.claim_token||''),model_label:String(args.model_label||'CLAUDE'),output_rows:args.output_rows})});const j=await r.json().catch(()=>({error:'INVALID_RESPONSE'}));if(!r.ok)return result(id,{isError:true,...content({status:j?.error==='INVALID_CONTRIBUTION'?'A_REFAIRE':'ERREUR_VALIDATION'})});return result(id,content({status:'MERCI_CONTRIBUTION_RECUE'}));}
return error(id,-32601,'Unknown tool');}catch(e){console.error(e);return result(id,{isError:true,...content({status:'ERREUR'})});}}
return error(id,-32601,'Method not found');});
