import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SOCIAL_CONFIG, socializeContribution } from './social_engine.ts';
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type','access-control-allow-methods':'GET, POST, OPTIONS'};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const supabase=createClient(Deno.env.get('SUPABASE_URL'),Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});
const BUCKET='asv2-payloads-v1';
const FACTORS=['prior_vote_inertia','turnout_habit','personal_economic_conditions','employment_and_income','social_protection_and_public_services','policy_program_fit','governance_and_institutions','territorial_rural_fit','government_reward_punishment','local_candidate_context','other_verified_context'];
const REASONS=new Set(['PRIOR_VOTE_INERTIA','PRIOR_ABSTENTION_INERTIA','TURNOUT_HABIT','ECONOMIC_SELF_INTEREST','EMPLOYMENT_INCOME_FIT','SOCIAL_PROTECTION_PUBLIC_SERVICES_FIT','POLICY_PROGRAM_FIT','GOVERNANCE_INSTITUTIONAL_FIT','TERRITORIAL_RURAL_FIT','GOVERNMENT_REWARD','GOVERNMENT_PUNISHMENT','LOCAL_CANDIDATE_STRENGTH','LOCAL_CANDIDATE_WEAKNESS','ATTITUDE_POSTERIOR','OTHER_VERIFIED_CONTEXT','NO_DIRECTIONAL_EVIDENCE']);
const ROW_KEYS=['anonymous_election_id','anonymous_territory_id','condition_id','batch_id','weighted_archetype_id','turnout_probability','conditional_party_probabilities','factor_importance','reason_codes'].sort();
const hexSha=async(v)=>{const b=new TextEncoder().encode(JSON.stringify(v));const h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('')};
async function storageReady(){const {data,error}=await supabase.storage.from(BUCKET).download('_READY.json');return !error&&!!data}
async function readText(path){const {data,error}=await supabase.storage.from(BUCKET).download(path);if(error||!data)throw new Error('PAYLOAD_NOT_READY');return await data.text()}
async function readJson(path){return JSON.parse(await readText(path))}
function sameKeys(obj,keys){return obj&&typeof obj==='object'&&!Array.isArray(obj)&&JSON.stringify(Object.keys(obj).sort())===JSON.stringify([...keys].sort())}
function validateRows(rows,w,voterBatch){if(!Array.isArray(rows)||rows.length!==32)return{ok:false,error:'ROW_COUNT'};const voters=voterBatch?.voter_archetypes||[],partyIds=[...(voterBatch?.available_party_ids||[])].sort();if(voters.length!==32||partyIds.length!==9)return{ok:false,error:'VOTER_BATCH_INVALID'};const seen=new Set();for(let i=0;i<32;i++){const r=rows[i],v=voters[i];if(!sameKeys(r,ROW_KEYS))return{ok:false,error:'ROW_SHAPE',row:i};if(r.anonymous_election_id!==w.anonymous_election_id||r.anonymous_territory_id!==w.anonymous_territory_id||r.condition_id!==w.condition_id||r.batch_id!==w.batch_id)return{ok:false,error:'WORK_IDENTITY',row:i};if(String(r.weighted_archetype_id)!==String(v.weighted_archetype_id))return{ok:false,error:'ARCHETYPE_ORDER',row:i};if(seen.has(r.weighted_archetype_id))return{ok:false,error:'DUPLICATE_ARCHETYPE',row:i};seen.add(r.weighted_archetype_id);const u=Number(r.turnout_probability);if(!Number.isFinite(u)||u<0||u>1)return{ok:false,error:'TURNOUT',row:i};if(!sameKeys(r.conditional_party_probabilities,partyIds))return{ok:false,error:'PARTY_KEYS',row:i};const p=partyIds.map(k=>Number(r.conditional_party_probabilities[k]));if(p.some(x=>!Number.isFinite(x)||x<0||x>1)||Math.abs(p.reduce((a,b)=>a+b,0)-1)>1e-9)return{ok:false,error:'PARTY_SIMPLEX',row:i};if(!sameKeys(r.factor_importance,FACTORS))return{ok:false,error:'FACTOR_KEYS',row:i};const f=FACTORS.map(k=>Number(r.factor_importance[k]));if(f.some(x=>!Number.isFinite(x)||x<0||x>1)||Math.abs(f.reduce((a,b)=>a+b,0)-1)>1e-9)return{ok:false,error:'FACTOR_SIMPLEX',row:i};if(!Array.isArray(r.reason_codes)||r.reason_codes.length<1||r.reason_codes.length>4||new Set(r.reason_codes).size!==r.reason_codes.length||r.reason_codes.some(x=>!REASONS.has(x)))return{ok:false,error:'REASON_CODES',row:i}}return{ok:true}}
async function assignmentContext(token){const {data:a,error:ae}=await supabase.from('asv2_assignments').select('assignment_id,cohort_id,work_id,status,expires_at,provider').eq('claim_token',token).single();if(ae||!a)throw new Error('UNKNOWN_CLAIM');const {data:w,error:we}=await supabase.from('asv2_work_items').select('work_id,anonymous_election_id,anonymous_territory_id,condition_id,batch_id').eq('work_id',a.work_id).single();if(we||!w)throw new Error('WORK_NOT_FOUND');const voterPath=`voter_batches/${w.anonymous_election_id}/${w.anonymous_territory_id}/${w.batch_id}.json`;const voterBatch=await readJson(voterPath);return{a,w,voterBatch,voterPath}}
async function buildSocialPreview(ctx,rows,modelLabel,r0Sha){const sourceKey=`voter_batches/${ctx.w.anonymous_election_id}/${ctx.w.anonymous_territory_id}/${ctx.w.batch_id}.json`;const s=await socializeContribution(rows,ctx.voterBatch.voter_archetypes,sourceKey);const payload={assignment_id:ctx.a.assignment_id,cohort_id:ctx.a.cohort_id,work_id:ctx.a.work_id,provider:ctx.a.provider||'other',model_label:modelLabel,r0_sha256:r0Sha,engine_version:'ATLAS_SOCIAL_LIVE_EDGE_V1',config_version:SOCIAL_CONFIG.schema_version,config_status:SOCIAL_CONFIG.status,graph_sha256:s.graph_sha256,profiles:s.profiles,graph:s.graph,summary:s.summary};const {error}=await supabase.from('asv2_social_previews').upsert(payload,{onConflict:'assignment_id'});if(error)throw error;return s.summary}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});const url=new URL(req.url),path=url.pathname.replace(/\/+$/,'');try{
 if(req.method==='GET'&&path.endsWith('/status')){const{data,error}=await supabase.rpc('asv2_public_collection_status');if(error)throw error;const s=data?.[0]||null,ready=await storageReady();return json({state:s?.state||'COLLECTING',completed:Number(s?.completed||0),target:Number(s?.target_work_items||2944),progress:Number(s?.target_work_items||0)?Number(s?.completed||0)/Number(s?.target_work_items):0,results_revealed:false,ready});}
 if(req.method==='POST'&&path.endsWith('/claim')){if(!(await storageReady()))return json({error:'COLLECTION_NOT_READY'},409);const body=await req.json().catch(()=>({})),provider=String(body.provider||'other').toLowerCase();if(!['chatgpt','claude','other'].includes(provider))return json({error:'UNKNOWN_ASSISTANT'},400);const{data,error}=await supabase.rpc('asv2_claim_public_work_item',{p_provider:provider});if(error){const msg=error.message||'';if(msg.includes('NO_READY_WORK_AVAILABLE'))return json({error:'NO_CONTRIBUTION_AVAILABLE'},409);throw error}const x=data?.[0];const{data:w,error:we}=await supabase.from('asv2_work_items').select('anonymous_election_id,anonymous_territory_id,condition_id,batch_id').eq('work_id',x.work_id).single();if(we)throw we;const voter=`voter_batches/${w.anonymous_election_id}/${w.anonymous_territory_id}/${w.batch_id}.json`,context=`contexts/${w.anonymous_election_id}/${w.condition_id}/${w.anonymous_territory_id}.json`;try{const[judge_prompt,output_schema,ctx,voter_batch]=await Promise.all([readText('as2_full_environment_prompt_v2.md'),readJson('as2_full_environment_output_schema_v2.json'),readJson(context),readJson(voter)]);const files={prompt:'data/contrib/prompt.txt',schema:'data/contrib/schema.json',context:`data/contrib/contexts/${w.anonymous_election_id}/${w.condition_id}/${w.anonymous_territory_id}.json.gz`,voter:`data/contrib/voter_batches/${w.anonymous_election_id}/${w.anonymous_territory_id}/${w.batch_id}.json.gz`};return json({assignment_id:x.assignment_id,claim_token:x.claim_token,expires_at:x.expires_at,work_id:x.work_id,files,payload:{judge_prompt,output_schema,context:ctx,voter_batch}})}catch(e){await supabase.from('asv2_assignments').delete().eq('assignment_id',x.assignment_id);throw e;}}
 if(req.method==='POST'&&path.endsWith('/submit')){const body=await req.json(),token=String(body.claim_token||'');if(!token)return json({error:'MISSING_CLAIM'},400);const ctx=await assignmentContext(token);const check=validateRows(body.output_rows,ctx.w,ctx.voterBatch);if(!check.ok)return json({error:'INVALID_CONTRIBUTION',detail:check},422);const modelLabel=String(body.model_label||'UNSPECIFIED'),sha=await hexSha(body.output_rows);const{data,error}=await supabase.rpc('asv2_submit_assignment',{p_claim_token:token,p_model_label:modelLabel,p_output_rows:body.output_rows,p_output_sha256:sha,p_validation:{ok:true,work_identity:true,row_order:true,schema_v2:true}});if(error)throw error;let social_status='READY',social_summary=null;try{social_summary=await buildSocialPreview(ctx,body.output_rows,modelLabel,sha)}catch(e){social_status='PENDING_RETRY';console.error('social-preview',e)}return json({status:'VALIDATED',social_status,social_summary,...data?.[0]});}
 return json({name:'Société artificielle du Maroc'});
}catch(e){console.error(e);return json({error:String(e?.message||'SERVER_ERROR')},500)}});
