export const SOCIAL_CONFIG = {
  schema_version: 'ATLAS_SOCIAL_LIVE_PREVIEW_V1',
  status: 'ILLUSTRATIVE_NOT_CALIBRATED',
  graph_seed: 'ATLAS_SOCIAL_V1',
  lambdas: { family: 0.18, work: 0.10, neighborhood: 0.06 },
  top_k: { family: 4, work: 6, neighborhood: 8 },
  min_score: { family: 0.34, work: 0.32, neighborhood: 0.28 },
};
const RELATIONS=['family','work','neighborhood'];
const EPS=1e-12;
const clip=(x,lo=0,hi=1)=>x<lo?lo:x>hi?hi:x;
const num=(v,k,d=.5)=>{const x=Number(v?.[k]);return Number.isFinite(x)?x:Number(d)};
const close=(a,b,s)=>clip(1-Math.abs(Number(a)-Number(b))/Number(s));
const eq=(a,b)=>{const miss=new Set(['MISSING','UNKNOWN','NOT_FOUND',null,'']);return miss.has(a)||miss.has(b)?0:(a===b?1:0)};
const prefixEq=(a,b)=>{if(!a||!b)return 0;return String(a).split(' - ')[0].trim()===String(b).split(' - ')[0].trim()?1:0};
const age=v=>Number.isFinite(Number(v?.age_years))?Number(v.age_years):({"18_24":21,"25_34":29,"35_44":39,"45_59":51,"60_PLUS":68}[v?.age_band]??40);
const hhFamily=v=>{const h=v?.household_type||'';if(h.includes('seule personne'))return'single';if(h.includes('Mère avec')||h.includes('Père avec'))return'single_parent';if(h.includes('élargi')||h.includes('composite')||h.includes('polygame'))return'extended';if(h.includes('Couple'))return'nuclear';return h?String(h):'unknown'};
const qv=v=>num(v,'latent_national_quintile',.6), ses=v=>num(v,'latent_ses_decile',.5);
const edu=v=>({"Aucun niveau d'études":0,"Préscolaire":.12,"Primaire":.30,"Secondaire collégial":.52,"Secondaire qualifiant":.74,"Supérieur":1}[v?.education_level]??.30);
const employed=v=>v?.activity_status==='ACTIVE_EMPLOYED';
const familyScore=(a,b)=>{const gap=Math.abs(age(a)-age(b)),af=Math.max(Math.exp(-gap/16),.82*Math.exp(-Math.abs(gap-27)/15)),ha=Math.max(1,num(a,'household_size',5)),hb=Math.max(1,num(b,'household_size',5));return .25*eq(hhFamily(a),hhFamily(b))+.18*close(qv(a),qv(b),.55)+.13*eq(a?.urban_rural,b?.urban_rural)+.14*close(ha,hb,6)+.10*eq(a?.marital_status,b?.marital_status)+.15*af+.05*(1-eq(a?.sex,b?.sex))};
const workScore=(a,b)=>!employed(a)||!employed(b)?0:.34*prefixEq(a?.industry_sector,b?.industry_sector)+.14*prefixEq(a?.occupation_group,b?.occupation_group)+.08*eq(a?.professional_status,b?.professional_status)+.14*close(qv(a),qv(b),.55)+.10*eq(a?.urban_rural,b?.urban_rural)+.10*close(edu(a),edu(b),.8)+.10*close(age(a),age(b),35);
const neighborhoodScore=(a,b)=>.34*eq(a?.urban_rural,b?.urban_rural)+.24*close(qv(a),qv(b),.55)+.16*close(ses(a),ses(b),.65)+.09*close(age(a),age(b),45)+.08*eq(hhFamily(a),hhFamily(b))+.05*prefixEq(a?.industry_sector,b?.industry_sector)+.04*close(edu(a),edu(b),1);
const SCORE={family:familyScore,work:workScore,neighborhood:neighborhoodScore};
const archetypeId=v=>String(v?.weighted_archetype_id||v?.archetype_id||'');
async function sha256Text(text){const ab=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(ab)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function sha256Json(obj){return sha256Text(JSON.stringify(obj))}
async function stableUnit(...parts){const hex=await sha256Text(parts.map(String).join('\x1f'));return Number(BigInt('0x'+hex.slice(0,16)))/Number(0xffffffffffffffffn)}
async function relationTargets(voters,i,relation){const src=voters[i],scored=[];for(let j=0;j<voters.length;j++){if(j===i)continue;const score=SCORE[relation](src,voters[j]);if(score<SOCIAL_CONFIG.min_score[relation])continue;const jitter=(await stableUnit(SOCIAL_CONFIG.graph_seed,relation,archetypeId(src),archetypeId(voters[j])))*1e-7;scored.push([score+jitter,j])}scored.sort((a,b)=>b[0]-a[0]||a[1]-b[1]);const sel=scored.slice(0,SOCIAL_CONFIG.top_k[relation]);if(!sel.length)return[];const raw=sel.map(x=>Math.max(1e-9,x[0])),total=raw.reduce((a,b)=>a+b,0);return sel.map((x,k)=>({i:x[1],w:Number((raw[k]/total).toFixed(12))}))}
export async function buildGraph(voters,sourceKey){const ids=voters.map(archetypeId);if(new Set(ids).size!==ids.length)throw new Error('DUPLICATE_ARCHETYPE_IDS');const nodes=[];for(let i=0;i<voters.length;i++){const relations={};for(const r of RELATIONS)relations[r]=await relationTargets(voters,i,r);nodes.push({id:ids[i],relations})}return{schema_version:'ATLAS_SOCIAL_GRAPH_V1',semantics:'archetype_exposure_distribution_not_literal_person_edges',source_key:sourceKey,seed:SOCIAL_CONFIG.graph_seed,top_k:{...SOCIAL_CONFIG.top_k},min_score:{...SOCIAL_CONFIG.min_score},nodes}}
function norm(prob){const keys=Object.keys(prob),vals=keys.map(k=>Math.max(EPS,Number(prob[k]))),s=vals.reduce((a,b)=>a+b,0),out={};keys.forEach((k,i)=>out[k]=vals[i]/s);return out}
function entropy01(prob){const vals=Object.values(norm(prob)),n=vals.length;if(n<=1)return 0;const h=-vals.reduce((s,p)=>s+p*Math.log(Math.max(EPS,p)),0);return clip(h/Math.log(n))}
function logit(p){p=clip(Number(p),1e-9,1-1e-9);return Math.log(p/(1-p))}function sigmoid(x){if(x>=0){const z=Math.exp(-x);return 1/(1+z)}const z=Math.exp(x);return z/(1+z)}
function partyKeys(rows){return Object.keys(rows[0].conditional_party_probabilities).sort()}
function partyExposure(rows,edges,keys){if(!edges.length)return null;const acc=Object.fromEntries(keys.map(k=>[k,0]));let mass=0;for(const e of edges){const w=Number(e.w),p=rows[e.i].conditional_party_probabilities;for(const k of keys)acc[k]+=w*Number(p[k]);mass+=w}if(mass<=0)return null;const tmp={};for(const k of keys)tmp[k]=acc[k]/mass;return norm(tmp)}
function turnoutExposure(rows,edges){if(!edges.length)return null;let total=0,mass=0;for(const e of edges){const w=Number(e.w);total+=w*Number(rows[e.i].turnout_probability);mass+=w}return mass<=0?null:clip(total/mass,1e-9,1-1e-9)}
function exposure(rows,graph,i){const keys=partyKeys(rows),parties={},turnout={};for(const r of RELATIONS){const edges=graph.nodes[i].relations[r]||[];parties[r]=partyExposure(rows,edges,keys);turnout[r]=turnoutExposure(rows,edges)}return[parties,turnout]}
function poolParty(selfP,exps,lams){const keys=Object.keys(selfP).sort(),cur=norm(selfP),sus=.12+.88*entropy01(cur);let total=0;for(const r of RELATIONS)if(exps[r]!=null)total+=Math.max(0,Number(lams[r]||0));if(total<=0)return[{...selfP},sus];const scale=Math.min(.92,total)/total,scores={};for(const k of keys){const lp=Math.log(Math.max(EPS,Number(cur[k])));let d=0;for(const r of RELATIONS){if(exps[r]==null)continue;const lam=Math.max(0,Number(lams[r]||0))*scale;d+=lam*(Math.log(Math.max(EPS,Number(exps[r][k])))-lp)}scores[k]=Math.exp(lp+sus*d)}return[norm(scores),sus]}
function poolTurnout(selfT,exps,lams){const t=clip(Number(selfT),1e-9,1-1e-9),amb=1-Math.min(1,2*Math.abs(t-.5)),sus=.18+.82*amb;let total=0;for(const r of RELATIONS)if(exps[r]!=null)total+=Math.max(0,Number(lams[r]||0));if(total<=0)return[Number(selfT),sus];const scale=Math.min(.92,total)/total,base=logit(t);let d=0;for(const r of RELATIONS){if(exps[r]==null)continue;const lam=Math.max(0,Number(lams[r]||0))*scale;d+=lam*(logit(exps[r])-base)}return[sigmoid(base+sus*d),sus]}
export function updateRound(rows,graph,roundName='R1'){if(rows.length!==graph.nodes.length)throw new Error('ROW_GRAPH_COUNT_MISMATCH');const ids=rows.map(x=>String(x.weighted_archetype_id));for(let i=0;i<ids.length;i++)if(ids[i]!==String(graph.nodes[i].id))throw new Error('ROW_GRAPH_ORDER_MISMATCH');const lams=SOCIAL_CONFIG.lambdas,out=[];for(let i=0;i<rows.length;i++){const [pe,te]=exposure(rows,graph,i),[np,ps]=poolParty(rows[i].conditional_party_probabilities,pe,lams),[nt,ts]=poolTurnout(rows[i].turnout_probability,te,lams),r=structuredClone(rows[i]),oldp=rows[i].conditional_party_probabilities,oldt=Number(rows[i].turnout_probability),rels={};r.conditional_party_probabilities=np;r.turnout_probability=nt;for(const rel of RELATIONS)rels[rel]={lambda:lams[rel],contacts:(graph.nodes[i].relations[rel]||[]).length,party_exposure:pe[rel],turnout_exposure:te[rel]};r.social_influence={schema_version:'ATLAS_SOCIAL_DECISION_V1',round:roundName,synchronous:true,private_state_preserved_as_anchor:true,party_susceptibility:ps,turnout_susceptibility:ts,party_shift_l1:Object.keys(np).reduce((s,k)=>s+Math.abs(Number(np[k])-Number(oldp[k])),0),turnout_shift:nt-oldt,relations:rels};out.push(r)}return out}
export const safeProfiles=voters=>voters.map(v=>({weighted_archetype_id:archetypeId(v),age_band:v.age_band,age_years:v.age_years,sex:v.sex,urban_rural:v.urban_rural,education_level:v.education_level,activity_status:v.activity_status,latent_national_quintile:v.latent_national_quintile,latent_ses_decile:v.latent_ses_decile,household_type:v.household_type,household_size:v.household_size,marital_status:v.marital_status,industry_sector:v.industry_sector,professional_status:v.professional_status,occupation_group:v.occupation_group}));
const l1=(a,b)=>Object.keys(a).reduce((s,k)=>s+Math.abs(Number(a[k])-Number(b[k])),0);
export async function socializeContribution(rows,voters,sourceKey){const graph=await buildGraph(voters,sourceKey),r1=updateRound(rows,graph,'R1'),r2=updateRound(r1,graph,'R2');const n=rows.length,edges={family:0,work:0,neighborhood:0};for(const node of graph.nodes)for(const r of RELATIONS)edges[r]+=(node.relations[r]||[]).length;const avg=f=>f.reduce((a,b)=>a+b,0)/Math.max(1,f.length);const summary={schema_version:'ATLAS_SOCIAL_PREVIEW_SUMMARY_V1',status:'ILLUSTRATIVE_NOT_CALIBRATED',rows:n,edges,mean_r1_party_shift_l1:avg(r1.map((x,i)=>l1(rows[i].conditional_party_probabilities,x.conditional_party_probabilities))),mean_r2_from_r0_party_shift_l1:avg(r2.map((x,i)=>l1(rows[i].conditional_party_probabilities,x.conditional_party_probabilities))),mean_r1_turnout_abs_shift:avg(r1.map((x,i)=>Math.abs(Number(x.turnout_probability)-Number(rows[i].turnout_probability)))),mean_r2_from_r0_turnout_abs_shift:avg(r2.map((x,i)=>Math.abs(Number(x.turnout_probability)-Number(rows[i].turnout_probability))))};return{graph,graph_sha256:await sha256Json(graph),profiles:safeProfiles(voters),summary,r1,r2}}
