-- ATLAS Agent Society V2 — public collection anti-abuse policy V1.
-- Reconciliation migration: reproduces the final pre-outcome anti-abuse layer.

create table if not exists public.asv2_participants (
  participant_id uuid primary key default gen_random_uuid(),
  browser_hash text not null unique,
  first_ip_hash text not null,
  state text not null default 'ACTIVE' check (state in ('ACTIVE','BLOCKED')),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.asv2_participation_tickets (
  ticket_id uuid primary key default gen_random_uuid(),
  ticket_hash text not null unique,
  participant_id uuid not null references public.asv2_participants(participant_id) on delete cascade,
  browser_hash text not null,
  ip_hash text not null,
  scope text not null default 'WEB_OR_MCP' check (scope in ('WEB_OR_MCP','WEB_ONLY','MCP_ONLY')),
  status text not null default 'ACTIVE' check (status in ('ACTIVE','CONSUMED','REVOKED','EXPIRED')),
  turnstile_meta jsonb not null default '{}'::jsonb,
  issued_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz
);

create table if not exists public.asv2_security_config (
  config_id text primary key,
  ip_pepper text not null,
  turnstile_required boolean not null default true,
  turnstile_site_key text,
  ticket_ttl_seconds integer not null default 300 check (ticket_ttl_seconds between 60 and 3600),
  max_active_claims_per_participant integer not null default 1 check (max_active_claims_per_participant > 0),
  max_active_claims_per_ip integer not null default 3 check (max_active_claims_per_ip > 0),
  max_claims_per_ip_24h integer not null default 10 check (max_claims_per_ip_24h > 0),
  max_claims_per_participant_24h integer not null default 3 check (max_claims_per_participant_24h > 0),
  max_completed_per_participant_24h integer not null default 3 check (max_completed_per_participant_24h > 0),
  max_tickets_per_participant_hour integer not null default 5 check (max_tickets_per_participant_hour > 0),
  max_tickets_per_ip_hour integer not null default 20 check (max_tickets_per_ip_hour > 0),
  cooldown_after_expired_24h integer not null default 5 check (cooldown_after_expired_24h > 0),
  quarantine_score_threshold integer not null default 100 check (quarantine_score_threshold > 0),
  updated_at timestamptz not null default now()
);

insert into public.asv2_security_config(config_id,ip_pepper)
values('PUBLIC_V1',encode(gen_random_bytes(32),'hex')) on conflict(config_id) do nothing;
update public.asv2_security_config set
  turnstile_required=true,ticket_ttl_seconds=300,
  max_active_claims_per_participant=1,max_active_claims_per_ip=3,
  max_claims_per_ip_24h=10,max_claims_per_participant_24h=3,
  max_completed_per_participant_24h=3,max_tickets_per_participant_hour=5,
  max_tickets_per_ip_hour=20,cooldown_after_expired_24h=5,
  quarantine_score_threshold=100,updated_at=now()
where config_id='PUBLIC_V1';

create table if not exists public.asv2_security_events (
  event_id bigint generated by default as identity primary key,
  participant_id uuid references public.asv2_participants(participant_id) on delete set null,
  assignment_id uuid references public.asv2_assignments(assignment_id) on delete set null,
  ip_hash text,browser_hash text,event_type text not null,
  detail jsonb not null default '{}'::jsonb,created_at timestamptz not null default now()
);

alter table public.asv2_assignments add column if not exists participant_id uuid references public.asv2_participants(participant_id) on delete set null;
alter table public.asv2_assignments add column if not exists browser_hash text;
alter table public.asv2_assignments add column if not exists ip_hash text;
alter table public.asv2_assignments add column if not exists channel text;
alter table public.asv2_assignments add column if not exists scientific_status text;
alter table public.asv2_assignments add column if not exists abuse_score integer;
alter table public.asv2_assignments add column if not exists abuse_flags jsonb;
alter table public.asv2_assignments add column if not exists behavior_fingerprint text;
alter table public.asv2_assignments add column if not exists behavior_profile jsonb;
alter table public.asv2_assignments add column if not exists submission_latency_seconds numeric;

create index if not exists asv2_assignments_participant_idx on public.asv2_assignments(participant_id,claimed_at desc);
create index if not exists asv2_assignments_ip_idx on public.asv2_assignments(ip_hash,claimed_at desc);
create index if not exists asv2_assignments_fingerprint_idx on public.asv2_assignments(behavior_fingerprint) where behavior_fingerprint is not null;
create index if not exists asv2_security_events_ip_idx on public.asv2_security_events(ip_hash,created_at desc);
create index if not exists asv2_security_events_participant_idx on public.asv2_security_events(participant_id,created_at desc);

alter table public.asv2_participants enable row level security;
alter table public.asv2_participation_tickets enable row level security;
alter table public.asv2_security_config enable row level security;
alter table public.asv2_security_events enable row level security;
revoke all on public.asv2_participants from public,anon,authenticated;
revoke all on public.asv2_participation_tickets from public,anon,authenticated;
revoke all on public.asv2_security_config from public,anon,authenticated;
revoke all on public.asv2_security_events from public,anon,authenticated;
grant all on public.asv2_participants to service_role;
grant all on public.asv2_participation_tickets to service_role;
grant all on public.asv2_security_config to service_role;
grant all on public.asv2_security_events to service_role;

create or replace function public.asv2_issue_participation_ticket(p_browser_hash text,p_ip_hash text,p_ticket_hash text,p_turnstile_meta jsonb default '{}'::jsonb)
returns table(participant_id uuid,ticket_id uuid,expires_at timestamptz)
language plpgsql security definer set search_path=public,pg_temp as $$
declare c public.asv2_security_config%rowtype; p public.asv2_participants%rowtype; t public.asv2_participation_tickets%rowtype; n bigint;
begin
 if coalesce(length(p_browser_hash),0)<32 or coalesce(length(p_ip_hash),0)<32 or coalesce(length(p_ticket_hash),0)<32 then raise exception 'SECURITY_ID_INVALID'; end if;
 select * into c from public.asv2_security_config where config_id='PUBLIC_V1'; if c.config_id is null then raise exception 'SECURITY_CONFIG_MISSING'; end if;
 insert into public.asv2_participants(browser_hash,first_ip_hash) values(p_browser_hash,p_ip_hash) on conflict(browser_hash) do update set last_seen_at=now() returning * into p;
 if p.state<>'ACTIVE' then raise exception 'PARTICIPANT_BLOCKED'; end if;
 select count(*) into n from public.asv2_security_events where ip_hash=p_ip_hash and event_type='TICKET_ISSUED' and created_at>=now()-interval '1 hour'; if n>=c.max_tickets_per_ip_hour then raise exception 'RATE_LIMIT_TICKET_IP_HOURLY'; end if;
 select count(*) into n from public.asv2_security_events where participant_id=p.participant_id and event_type='TICKET_ISSUED' and created_at>=now()-interval '1 hour'; if n>=c.max_tickets_per_participant_hour then raise exception 'RATE_LIMIT_TICKET_PARTICIPANT_HOURLY'; end if;
 update public.asv2_participation_tickets set status='EXPIRED' where participant_id=p.participant_id and status='ACTIVE' and expires_at<now();
 update public.asv2_participation_tickets set status='REVOKED' where participant_id=p.participant_id and status='ACTIVE';
 insert into public.asv2_participation_tickets(ticket_hash,participant_id,browser_hash,ip_hash,turnstile_meta,expires_at) values(p_ticket_hash,p.participant_id,p_browser_hash,p_ip_hash,coalesce(p_turnstile_meta,'{}'::jsonb),now()+make_interval(secs=>c.ticket_ttl_seconds)) returning * into t;
 insert into public.asv2_security_events(participant_id,ip_hash,browser_hash,event_type,detail) values(p.participant_id,p_ip_hash,p_browser_hash,'TICKET_ISSUED',jsonb_build_object('ticket_id',t.ticket_id));
 participant_id:=p.participant_id;ticket_id:=t.ticket_id;expires_at:=t.expires_at;return next;
end $$;

create or replace function public.asv2_claim_public_work_item_v2(p_provider text,p_ticket_hash text,p_browser_hash text,p_channel text default 'web')
returns table(assignment_id uuid,claim_token uuid,work_id text,expires_at timestamptz,participant_id uuid)
language plpgsql security definer set search_path=public,pg_temp as $$
declare c public.asv2_security_config%rowtype;t public.asv2_participation_tickets%rowtype;w public.asv2_work_items%rowtype;a public.asv2_assignments%rowtype;s text;n bigint;
begin
 if p_provider not in ('chatgpt','claude','other') then raise exception 'UNKNOWN_PROVIDER';end if;if p_channel not in ('web','mcp') then raise exception 'UNKNOWN_CHANNEL';end if;
 select * into c from public.asv2_security_config where config_id='PUBLIC_V1';if c.config_id is null then raise exception 'SECURITY_CONFIG_MISSING';end if;
 select * into t from public.asv2_participation_tickets where ticket_hash=p_ticket_hash for update;if t.ticket_id is null then raise exception 'INVALID_PARTICIPATION_TICKET';end if;if t.status<>'ACTIVE' then raise exception 'PARTICIPATION_TICKET_USED';end if;if t.expires_at<now() then update public.asv2_participation_tickets set status='EXPIRED' where ticket_id=t.ticket_id;raise exception 'PARTICIPATION_TICKET_EXPIRED';end if;if p_channel='web' and t.browser_hash<>p_browser_hash then raise exception 'PARTICIPATION_TICKET_BROWSER_MISMATCH';end if;
 select state into s from public.asv2_cohorts where cohort_id='AS2_PUBLIC_V1';if s is null then raise exception 'UNKNOWN_COHORT';end if;if s<>'COLLECTING' then raise exception 'COHORT_NOT_COLLECTING';end if;
 update public.asv2_assignments set status='EXPIRED' where cohort_id='AS2_PUBLIC_V1' and status='CLAIMED' and expires_at<now();
 select count(*) into n from public.asv2_assignments where cohort_id='AS2_PUBLIC_V1' and participant_id=t.participant_id and status='CLAIMED' and expires_at>=now();if n>=c.max_active_claims_per_participant then raise exception 'RATE_LIMIT_ACTIVE_PARTICIPANT';end if;
 select count(*) into n from public.asv2_assignments where cohort_id='AS2_PUBLIC_V1' and ip_hash=t.ip_hash and status='CLAIMED' and expires_at>=now();if n>=c.max_active_claims_per_ip then raise exception 'RATE_LIMIT_ACTIVE_IP';end if;
 select count(*) into n from public.asv2_security_events where ip_hash=t.ip_hash and event_type='CLAIM_GRANTED' and created_at>=now()-interval '24 hours';if n>=c.max_claims_per_ip_24h then raise exception 'RATE_LIMIT_IP_24H';end if;
 select count(*) into n from public.asv2_security_events where participant_id=t.participant_id and event_type='CLAIM_GRANTED' and created_at>=now()-interval '24 hours';if n>=c.max_claims_per_participant_24h then raise exception 'RATE_LIMIT_PARTICIPANT_CLAIMS_24H';end if;
 select count(*) into n from public.asv2_assignments where cohort_id='AS2_PUBLIC_V1' and participant_id=t.participant_id and status='COMPLETED' and completed_at>=now()-interval '24 hours';if n>=c.max_completed_per_participant_24h then raise exception 'RATE_LIMIT_PARTICIPANT_COMPLETED_24H';end if;
 select count(*) into n from public.asv2_assignments where cohort_id='AS2_PUBLIC_V1' and ip_hash=t.ip_hash and status='EXPIRED' and claimed_at>=now()-interval '24 hours';if n>=c.cooldown_after_expired_24h then raise exception 'COOLDOWN_EXPIRED_CLAIMS';end if;
 select wi.* into w from public.asv2_work_items wi where wi.payload_ready=true and wi.payload is not null and not exists(select 1 from public.asv2_assignments x where x.cohort_id='AS2_PUBLIC_V1' and x.work_id=wi.work_id and x.status in ('CLAIMED','COMPLETED')) order by md5(wi.work_id||'|'||t.ticket_id::text) for update of wi skip locked limit 1;if w.work_id is null then raise exception 'NO_READY_WORK_AVAILABLE';end if;
 insert into public.asv2_assignments(cohort_id,work_id,status,provider,participant_id,browser_hash,ip_hash,channel) values('AS2_PUBLIC_V1',w.work_id,'CLAIMED',p_provider,t.participant_id,t.browser_hash,t.ip_hash,p_channel) returning * into a;
 update public.asv2_participation_tickets set status='CONSUMED',consumed_at=now() where ticket_id=t.ticket_id;
 insert into public.asv2_security_events(participant_id,assignment_id,ip_hash,browser_hash,event_type,detail) values(t.participant_id,a.assignment_id,t.ip_hash,t.browser_hash,'CLAIM_GRANTED',jsonb_build_object('provider',p_provider,'channel',p_channel,'work_id',w.work_id));
 assignment_id:=a.assignment_id;claim_token:=a.claim_token;work_id:=a.work_id;expires_at:=a.expires_at;participant_id:=t.participant_id;return next;
end $$;

create or replace function public.asv2_finalize_assignment_v2(p_claim_token uuid,p_model_label text,p_output_rows jsonb,p_output_sha256 text,p_validation jsonb,p_scientific_status text,p_abuse_score integer,p_abuse_flags jsonb,p_behavior_fingerprint text,p_behavior_profile jsonb,p_submission_latency_seconds numeric)
returns table(cohort_id text,work_id text,assignment_id uuid,final_status text,scientific_status text,completed_at timestamptz)
language plpgsql security definer set search_path=public,pg_temp as $$
declare a public.asv2_assignments%rowtype;fs text;
begin
 if p_scientific_status not in ('ACCEPTED','QUARANTINED') then raise exception 'INVALID_SCIENTIFIC_STATUS';end if;
 select * into a from public.asv2_assignments where claim_token=p_claim_token for update;if a.assignment_id is null then raise exception 'UNKNOWN_CLAIM';end if;if a.status='COMPLETED' then raise exception 'ALREADY_COMPLETED';end if;if a.status<>'CLAIMED' then raise exception 'CLAIM_NOT_ACTIVE';end if;if a.expires_at<now() then update public.asv2_assignments set status='EXPIRED' where assignment_id=a.assignment_id;raise exception 'CLAIM_EXPIRED';end if;
 fs:=case when p_scientific_status='ACCEPTED' then 'COMPLETED' else 'REJECTED' end;
 update public.asv2_assignments set status=fs,completed_at=now(),model_label=p_model_label,output_rows=p_output_rows,output_sha256=p_output_sha256,validation=p_validation,scientific_status=p_scientific_status,abuse_score=p_abuse_score,abuse_flags=coalesce(p_abuse_flags,'[]'::jsonb),behavior_fingerprint=p_behavior_fingerprint,behavior_profile=p_behavior_profile,submission_latency_seconds=p_submission_latency_seconds where assignment_id=a.assignment_id;
 insert into public.asv2_security_events(participant_id,assignment_id,ip_hash,browser_hash,event_type,detail) values(a.participant_id,a.assignment_id,a.ip_hash,a.browser_hash,case when p_scientific_status='ACCEPTED' then 'SUBMIT_ACCEPTED' else 'SUBMIT_QUARANTINED' end,jsonb_build_object('abuse_score',p_abuse_score,'flags',coalesce(p_abuse_flags,'[]'::jsonb)));
 cohort_id:=a.cohort_id;work_id:=a.work_id;assignment_id:=a.assignment_id;final_status:=fs;scientific_status:=p_scientific_status;completed_at:=now();return next;
end $$;

revoke all on function public.asv2_issue_participation_ticket(text,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.asv2_claim_public_work_item_v2(text,text,text,text) from public,anon,authenticated;
revoke all on function public.asv2_finalize_assignment_v2(uuid,text,jsonb,text,jsonb,text,integer,jsonb,text,jsonb,numeric) from public,anon,authenticated;
revoke all on function public.asv2_claim_public_work_item(text) from public,anon,authenticated;
revoke all on function public.asv2_claim_work_item(text) from public,anon,authenticated;
revoke all on function public.asv2_submit_assignment(uuid,text,jsonb,text,jsonb) from public,anon,authenticated;
grant execute on function public.asv2_issue_participation_ticket(text,text,text,jsonb) to service_role;
grant execute on function public.asv2_claim_public_work_item_v2(text,text,text,text) to service_role;
grant execute on function public.asv2_finalize_assignment_v2(uuid,text,jsonb,text,jsonb,text,integer,jsonb,text,jsonb,numeric) to service_role;
