import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SOCIAL_CONFIG, updateRound } from './social_engine.ts';
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type','access-control-allow-methods':'GET, OPTIONS'};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const supabase=createClient(Deno.env.get('SUPABASE_URL'),Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='GET')return json({error:'GET_ONLY'},405);const path=new URL(req.url).pathname.replace(/\/+$/,'');try{
 if(path.endsWith('/status')){const[{data,error},{data:c,error:ce}]=await Promise.all([supabase.rpc('asv2_public_social_status'),supabase.from('asv2_cohorts').select('revealed_at').eq('cohort_id','AS2_PUBLIC_V1').single()]);if(error)throw error;if(ce)throw ce;const s=data?.[0]||{};return json({...s,connected:true,results_revealed:!!c?.revealed_at,config:{status:SOCIAL_CONFIG.status,version:SOCIAL_CONFIG.schema_version,lambdas:SOCIAL_CONFIG.lambdas}})}
 if(path.endsWith('/sample')){const{data:c,error:ce}=await supabase.from('asv2_cohorts').select('state,revealed_at').eq('cohort_id','AS2_PUBLIC_V1').single();if(ce)throw ce;if(!c?.revealed_at)return json({locked:true,error:'RESULTS_NOT_REVEALED'},423);const{data:p,error:pe}=await supabase.from('asv2_social_previews').select('assignment_id,provider,model_label,profiles,graph,summary,created_at').eq('cohort_id','AS2_PUBLIC_V1').order('created_at',{ascending:false}).limit(1).maybeSingle();if(pe)throw pe;if(!p)return json({locked:false,available:false});const{data:a,error:ae}=await supabase.from('asv2_assignments').select('output_rows').eq('assignment_id',p.assignment_id).single();if(ae)throw ae;const r0=a.output_rows,r1=updateRound(r0,p.graph,'R1'),r2=updateRound(r1,p.graph,'R2');return json({locked:false,available:true,provider:p.provider,model_label:p.model_label,profiles:p.profiles,graph:p.graph,r0,r1,r2,summary:p.summary,config:{status:SOCIAL_CONFIG.status,version:SOCIAL_CONFIG.schema_version}})}
 return json({name:'ATLAS social live pipeline',config_status:SOCIAL_CONFIG.status});
}catch(e){console.error(e);return json({error:String(e?.message||'SERVER_ERROR')},500)}});
